---
name: React
description: Use Ruby to build Reactive User Interfaces
url: https://facebook.github.io
baseurl: "/"
permalink: "/blog/:year/:month/:day/:title.html"
paginate_path: "/blog/page:num/"
paginate: 5
timezone: America/Los_Angeles
# highlighter: pygments
defaults:
- scope:
    path: ''
    type: post
  values:
    layout: post
- scope:
    path: docs
    type: page
  values:
    layout: docs
exclude:
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- vendor/bundle
markdown: kramdown
# redcarpet:
#   extensions:
#   - fenced_code_blocks
#   - footnotes
sass:
  style: :compressed
  sass_dir: _css
gems:
- jekyll-redirect-from
- jekyll-paginate
react_version: 0.14.2
